<?xml version="1.0" encoding="UTF-8"?>
<!-- ADL SCORM 1.2 Content Packaging Extension Schema -->
<xs:schema targetNamespace="http://www.adlnet.org/xsd/adlcp_rootv1p2"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns="http://www.adlnet.org/xsd/adlcp_rootv1p2"
           elementFormDefault="qualified"
           attributeFormDefault="unqualified">
  <xs:attribute name="scormtype" default="asset">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:enumeration value="asset"/>
        <xs:enumeration value="sco"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:attribute>
  <xs:attribute name="masteryscore" type="xs:decimal"/>
  <xs:attribute name="datafromlms" type="xs:string"/>
  <xs:attribute name="prerequisites" type="xs:string"/>
  <xs:attribute name="maxtimeallowed" type="xs:string"/>
  <xs:attribute name="timelimitaction" default="continue,no message">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:enumeration value="exit,message"/>
        <xs:enumeration value="exit,no message"/>
        <xs:enumeration value="continue,message"/>
        <xs:enumeration value="continue,no message"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:attribute>
  <xs:element name="location" type="xs:string"/>
</xs:schema>
